baseURL: "https://leyijiang17.github.io/" 
title: Leyi's Website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 5 
        - name: Papers
          url: papers/
          weight: 1
        - name: Activities
          url: activities/
          weight: 2
        #- name: Data
        #  url: data/
        #  weight: 4 
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: "This website hosts Leyi Jiang's research papers, course materials, data, curriculum vitae, and contact information."
    author: Leyi Jiang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    #ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Leyi Jiang
          subtitle: "I am a PhD candidate at the Centre of Mathematics and Artificial Intelligence of the Max Planck Institute of Molecular Cell Biology and Genetics in Dresden, Germany, within the Algebraic Systems Biology group of Heather A. Harrington. My research focuses on developing and applying Topological Data Analysis to uncover the hidden structures within spatial sub-cellular biological data."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Activities
              url: activities/
            #- name: Data
            #  url: data/
            #- name: Books
            #  url: books/
            #- name: Courses
            #  url: courses/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            - name: Reading group
              url: https://angeloelsaliby.github.io/AppliedToricGeometry-ReadingGroup/

    socialIcons:
        #- name: CV
        #  url: cv.pdf
        - name: Email
          url: mailto:ljiang@mpi-cbg.de
        - name: Location
          url: location/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        #- name: Bluesky
        #  url: https://bsky.app/profile/pmichaillat.bsky.social
        #- name: LinkedIn
        #  url: https://linkedin.com/in/rosavandenende
        #- name: ORCID
        #  url: https://orcid.org/0000-0002-9417-1075


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Leyi Jiang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
